---
version: 2

updates:
  - directory: /
    package-ecosystem: bundler
    schedule:
      interval: daily
    versioning-strategy: increase

  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: daily
