---
defaults:
  - scope:
      path: '' # Everywhere
    values:
      author: Romain Marcadier-Muller
  - scope:
      path: _posts
    values:
      layout: post
encoding: UTF-8
future: true
gfm_quirks: paragraph_end
gist:
  noscript: false
highlighter: rouge
jailed: false
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  syntax_highlighter: rouge
lsi: false
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
timezone: Europe/Paris
safe: true
strict_front_matter: true
# Site-specific configuration
lang: en_US
title: GeekyThoughts ∙ Blog
description: A blog about code.
collections:
  posts:
    output: true
    permalink: /:collection/:year-:month-:day/:title:output_ext
paginate: 20
paginate_path: /posts/page-:num/
