title: Crimson 11 Delight Petrichor
description: >-
  I'm a programming language wizard at Amazon Web Services in Luxembourg. This
  is my personal blog about software development, open source, programming
  languages, and related topics.
url: "https://romainmuller.dev"
baseurl: ''
keywords:
  - blog
  - development
  - tech

license:
  spdx: CC-BY-NC-ND-4.0
  name: Creative Commons Attribution Non Commercial No Derivatives 4.0 International

author:
  name: Romain Marcadier-Muller
  github:  RomainMuller
  keybase: romainmuller
  twitter: RomainMuller

# Build settings
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-paginate
  - jekyll-relative-links

encoding: UTF-8
timezone: Europe/Paris

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: post

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line-numbers: false
    block:
      line_numbers: true
      start_line: 1

relative_links:
  enabled: true
  collections: true

sass:
  style: compressed
  sourcemap: always

paginate: 10
paginate_path: '/page/:num/'

exclude:
  - .dependabot
  - .github
