title: Crimson 11 Delight Petrichor
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
url: "https://blog.geekythoughts.fr"
baseurl: ''
keywords:
  - blog
  - development
  - tech

license:
  spdx: CC-BY-NC-ND-4.0
  name: Creative Commons Attribution Non Commercial No Derivatives 4.0 International

author:
  name: Romain Marcadier-Muller
  github:  RomainMuller
  keybase: romainmuller
  twitter: RomainMuller

# Build settings
plugins:
  - jekyll-feed
  - jekyll-octicons
  - jekyll-paginate

encoding: UTF-8
timezone: Europe/Paris

defaults:
  - scope:
      path: ''
      type: 'posts'
    values:
      layout: post

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    span:
      line-numbers: false
    block:
      line_numbers: true
      start_line: 1

paginate: 10
paginate_path: '/page/:num/'

exclude:
  - .dependabot
  - .github
  - CNAME
