base_url = "https://www.romainmuller.dev"

title = "Orderly RAM"
description = "Reflections on Software Engineering, Open-Source, Photography, and more..."

default_language = "en"

build_search_index = true
compile_sass = true
generate_feed = true

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

[markdown]
external_links_no_follow = false
external_links_no_referrer = true
external_links_target_blank = true

highlight_code = true
highlight_theme = "solarized-dark"

render_emoji = true
smart_punctuation = true

[extra]
author = "Romain Marcadier"
keywords = ["Software Engineering", "Open-Source", "Blog"]
taxonomies = { categories = { display = "category", icon = "bookmarks-fill" }, tags = { display = "tag", icon = "tags-fill" } }
