name: Continuous Delivery

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ^2.6.x
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install
      - name: Jekyll Build
        run: bundle exec jekyll build
