name: Continuous Delivery

on:
  pull_request:
    branches:
      - source
  push:
    branches:
      - source

jobs:
  CI-CD:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout source
        uses: actions/checkout@v3.0.2
        with:
          path: source

      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x
      - name: Gem Cache
        uses: actions/cache@v2.1.4
        with:
          path: source/vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install Ruby Dependencies
        working-directory: ./source
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --deployment --jobs 4 --retry 3

      - name: Execute Build
        working-directory: ./source
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Checkout master
        uses: actions/checkout@v3.0.2
        with:
          path: master
          ref: master
          token: ${{secrets.GITHUB_PAT}}
      - name: Configure Git
        working-directory: ./master
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"

      - name: Preparing Release
        working-directory: ./master
        run: |
          rsync --delete --exclude=.git --recursive --verbose ../source/_site/ ./
          touch .nojekyll
          git add .
          git diff --exit-code --quiet HEAD || git commit -m "chore: publish from ${GITHUB_SHA}"

      - name: Release
        if: github.event_name == 'push'
        working-directory: ./master
        run: |
          git push origin master

  approve-dependabot:
    name: Approve Dependabot
    runs-on: ubuntu-latest
    needs: [CI-CD]

    if: github.event_name == 'pull_request' && (github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]')

    steps:
      - name: Request @dependabot auto-merge
        uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          command: 'squash and merge'
          github-token: ${{ secrets.GITHUB_PAT }}
          target: minor
